### ISSUE TITLE
Reverse Process

### ISSUE THREAD

**Issue by spidy0x0** [roryrjb/md5-file#29]
Hey,so i was wandering if there is a way to convert the generated hash back to the file again.
Can the process be reversed? :)

**Comment by LinusU** [comment]
This is virtually impossible for a few reasons. A hash algorithm is designed to only go one way, so you basically have to try every possible input and se if the hash matches, and even if you did that, there are multiple files that will produce the same hash (since the hash is only 128 bits).

The short answer is: it's not possible.
